default: &default
  tags:
    javascript:
      - javascript
      - js
      - meteor
      - meteorjs
    ruby:
      - ruby
      - ruby on rails
      - rails
      - ror
      - active record
    devops:
      - docker
    elasticsearch:
      - elastic
      - elk
      - kibana
      - logstash
    linux mint:
      - mint
    material design:
      - material
      - flat design
  websites:
    hackernews:
      url: https://news.ycombinator.com/newest
      dom_selector: '#hnmain table a[href^="http"]'
    # rubyflow:
    #   url: http://www.rubyflow.com
    humancoders:
      url: http://news.humancoders.com/items/newest
      dom_selector: '#items .title a[href^="/"]:not(.site_type_link)'
      prefix: http://news.humancoders.com

production:
  <<: *default
test:
  <<: *default
development:
  <<: *default
