default: &default
  tags:
    javascript:
      - javascript
      - js
      - meteor
      - meteorjs
    ruby:
      - ruby
      - 'ruby on rails'
      - rails
      - ror
      - 'active record'
    devops:
      - docker
    elasticsearch:
      - elastic
      - elk
      - kibana
      - logstash
    linux mint:
      - mint
    'material design':
      - material
      - flat
      - 'flat design'
  websites:
    hackernews:
      url: https://news.ycombinator.com/newest
      dom_selector:
        rel: nofollow
    rubyflow:
      url: http://www.rubyflow.com
production:
  <<: *default
test:
  <<: *default
development:
  <<: *default
