default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: harpoon
  password: harpoon
  host: localhost

development:
  <<: *default
  database: harpoon_development

test:
  <<: *default
  database: harpoon_test

production:
  <<: *default
  database: harpoon_production
