default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: scraper
  password: scraper
  host: localhost

development:
  <<: *default
  database: scraper_development

test:
  <<: *default
  database: scraper_test

production:
  <<: *default
  database: scraper_production
