default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: scrapper
  password: scrapper
  host: localhost

development:
  <<: *default
  database: scrapper_development

test:
  <<: *default
  database: scrapper_test

production:
  <<: *default
  database: scrapper_production
